# Generated by Django 5.0.2 on 2024-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='public'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
