# Generated by Django 5.0.2 on 2024-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app_1', '0004_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_extra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
