# Generated by Django 5.0.2 on 2024-02-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app_1', '0005_recipe_recipe_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_extra',
        ),
    ]
